# Generated by Django 3.1.7 on 2021-06-18 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor_name', models.CharField(max_length=20, verbose_name='name of used translator.')),
                ('standardizer_name', models.CharField(max_length=20, verbose_name='name of used translator.')),
                ('instrument', models.CharField(max_length=20, verbose_name='instrument name')),
                ('telescope', models.CharField(max_length=20, verbose_name='telescope')),
                ('science_program', models.CharField(max_length=30, verbose_name='science program image is a part of.')),
                ('obs_lon', models.FloatField(verbose_name='observatory longitude (deg)')),
                ('obs_lat', models.FloatField(verbose_name='observatory latitude (deg)')),
                ('obs_height', models.FloatField(verbose_name='observatory height (m)')),
                ('datetime_begin', models.DateTimeField(verbose_name='UTC at exposure start.')),
                ('datetime_end', models.DateTimeField(verbose_name='UTC at exposure end.')),
                ('exposure_duration', models.FloatField(verbose_name='exposure time (s)')),
                ('physical_filter', models.CharField(max_length=30, verbose_name='physical filter')),
            ],
        ),
        migrations.CreateModel(
            name='UploadInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date on which data was uploaded')),
                ('ip', models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP address of the uploader')),
            ],
        ),
        migrations.CreateModel(
            name='Wcs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wcs_radius', models.FloatField(verbose_name='distance between center and corner pixel')),
                ('wcs_center_x', models.FloatField(verbose_name='unit sphere coordinate of central pixel')),
                ('wcs_center_y', models.FloatField(verbose_name='unit sphere coordinate of central pixel')),
                ('wcs_center_z', models.FloatField(verbose_name='unit sphere coordinate of central pixel')),
                ('wcs_corner_x', models.FloatField(verbose_name='unit sphere coordinate of corner pixel')),
                ('wcs_corner_y', models.FloatField(verbose_name='unit sphere coordinate of corner pixel')),
                ('wcs_corner_z', models.FloatField(verbose_name='unit sphere coordinate of corner pixel')),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='upload.metadata')),
            ],
        ),
        migrations.AddField(
            model_name='metadata',
            name='upload_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='upload.uploadinfo'),
        ),
    ]
