# Generated by Django 3.1.7 on 2021-06-22 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnails',
            fields=[
                ('wcs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='upload.wcs')),
                ('large', models.CharField(max_length=20, verbose_name='location of large thumbnail')),
                ('small', models.CharField(max_length=20, verbose_name='location of small thumbnail')),
            ],
        ),
    ]
