# Generated by Django 3.1.7 on 2021-06-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_thumbnails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='physical_filter',
        ),
        migrations.AddField(
            model_name='metadata',
            name='filter',
            field=models.CharField(max_length=30, null=True, verbose_name='physical filter'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='exposure_duration',
            field=models.FloatField(null=True, verbose_name='exposure time (s)'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='instrument',
            field=models.CharField(max_length=20, null=True, verbose_name='instrument name'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='science_program',
            field=models.CharField(max_length=30, null=True, verbose_name='science program image is a part of.'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='telescope',
            field=models.CharField(max_length=20, null=True, verbose_name='telescope'),
        ),
    ]
