# Generated by Django 3.1.7 on 2021-09-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20210623_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnails',
            name='large',
            field=models.CharField(max_length=20, verbose_name='relative location of large thumbnail'),
        ),
        migrations.AlterField(
            model_name='thumbnails',
            name='small',
            field=models.CharField(max_length=20, verbose_name='relative location of small thumbnail'),
        ),
    ]
