# Generated by Django 3.1.7 on 2022-06-10 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_auto_20210906_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wcs',
            old_name='wcs_center_x',
            new_name='center_x',
        ),
        migrations.RenameField(
            model_name='wcs',
            old_name='wcs_center_y',
            new_name='center_y',
        ),
        migrations.RenameField(
            model_name='wcs',
            old_name='wcs_center_z',
            new_name='center_z',
        ),
        migrations.RenameField(
            model_name='wcs',
            old_name='wcs_corner_x',
            new_name='corner_x',
        ),
        migrations.RenameField(
            model_name='wcs',
            old_name='wcs_corner_y',
            new_name='corner_y',
        ),
        migrations.RenameField(
            model_name='wcs',
            old_name='wcs_corner_z',
            new_name='corner_z',
        ),
        migrations.RenameField(
            model_name='wcs',
            old_name='wcs_radius',
            new_name='radius',
        ),
        migrations.AlterField(
            model_name='wcs',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wcs', to='upload.metadata'),
        ),
    ]
