version: 1
disable_existing_loggers: False

filters: 
    require_debug_false: 
        (): django.utils.log.RequireDebugFalse    
    require_debug_true: 
        (): django.utils.log.RequireDebugTrue

formatters: 
    django.server: 
        (): django.utils.log.ServerFormatter
        format: "{levelname:<10} {asctime:<25} {message}"
        style: "{"

handlers: 
    console: 
        level: INFO
        filters: [require_debug_true]
        class: logging.StreamHandler
        formatter: django.server
    django.server: 
        level: INFO
        class: logging.StreamHandler
        formatter: django.server
    mail_admins: 
        level: ERROR
        filters: [require_debug_false]
        class: django.utils.log.AdminEmailHandler
    processing: 
        level: INFO
        class: logging.FileHandler
        filename: processing.log
        formatter: django.server

loggers: 
    django: 
        handlers: [console, mail_admins]
        level: INFO  
    django.server: 
        handlers: [django.server]
        level: INFO
        propagate: False
    astro_metadata_translator: 
        handlers: [console, processing]
        level: INFO
    upload: 
        handlers: [console, processing]
        level: INFO
    
    