debug: True
thumbnails:
  small_root: ../media/
  large_root: ../media/
data_root: ../static/upload/fits
astrometry_net:
  key:
  timeout: 200
gallery_image_count: 12
api_doc:
  title: "TrailBlazer API"
  version: "v1"
  description: "Trailblazer backend rest API"
  contact_email: "changethis@gmail.com"
  license:
    name: "MIT License"
    url: "https://github.com/dirac-institute/trailblazer/blob/main/LICENSE"
    