name: CI

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:
    branches:
    - main

jobs:
  linter:
    name: Code linter
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Run tests
      run: flake8
  main-test:
    needs: linter
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    name: 'py${{ matrix.python-version }} (ubuntu-latest)'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage
      - name: Install newest astro_metadata_translator
        run: |
          git clone https://github.com/lsst/astro_metadata_translator.git
          cd astro_metadata_translator
          pip install .
          cd ..
      - name: Run tests
        run: |
          cd trail
          coverage run --source="." manage.py test -v 2 -b
          coverage report
  tests:
    name: 'py${{ matrix.target.python }} (${{ matrix.target.os }})'
    runs-on: ${{ matrix.target.os }}
    needs: linter
    strategy:
      fail-fast: true
      matrix:
        target: [
        {"os": "macos-latest",   "python": "3.10"},
        {"os": "windows-latest", "python": "3.10"},
        ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.target.python }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install newest astro_metadata_translator
        run: |
          git clone https://github.com/lsst/astro_metadata_translator.git
          cd astro_metadata_translator/
          pip install .
          cd ..
      - name: Run tests
        run: |
          cd trail
          python manage.py test -v2 -b
          cd ..
