name: CI

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:
    branches:
    - main

jobs:
  linter:
    name: Code linter
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Run tests
      run: flake8

  tests:
    name: ${{ matrix.target.env }} (${{ matrix.target.os }})
    runs-on: ${{ matrix.target.os }}
    strategy:
      fail-fast: false
      matrix:
        target: [
        {"os": "macos-latest",   "python": "3.9", "env": "py3.9-test"},
        {"os": "windows-latest", "python": "3.9", "env": "py3.9-test"},
        {"os": "ubuntu-latest",  "python": "3.9", "env": "py3.9-test"},
        {"os": "ubuntu-latest",  "python": "3.8", "env": "py3.8-test"},
        {"os": "ubuntu-latest",  "python": "3.7", "env": "py3.7-test"}
        ]
        include:
          - toxargs: -v
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.target.python }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install newest astro_metadata_translator
        run: |
          git clone https://github.com/lsst/astro_metadata_translator.git
          cd astro_metadata_translator
          python setup.py install
          cd ..
      - name: Run tests
        run: |
          cd trail
          python manage.py test -v2 -b
          cd ..
